name: Deploy BananoLooker
on:
  push:
    branches:
      - bananolooker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build static assets
        env:
          REACT_APP_GOOGLE_MEASUREMENT_ID: ${{ secrets.REACT_APP_GOOGLE_MEASUREMENT_ID_BAN }}
        run: |
          npm install
          npm run build

      - name: Rsync deployment
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete --exclude=".env" --exclude="server/data/"
          path: "."
          remote_path: /var/www/www.bananolooker.com
          remote_host: ${{ secrets.DO_HOST_BAN }}
          remote_user: ${{ secrets.DO_USERNAME_BAN }}
          remote_key: ${{ secrets.DO_SSHKEY_BAN }}
